### PR TITLE
Use compiler generated dependency files

### PR DESCRIPTION
**Pull request by csoren**
This PR contains the changes necessary to support the new `--dependencies` compiler option.

As it stands, the Makefile will have to make an additional `cc68k` invocation plus a `sed` step.

The extra invocation is needed because `--dependencies` appears to skip the compilation step.

The `sed` step is needed because the generated dependency output will use the form `%.o: directory/%.c`, it will only use the filename stem and always append .o. This is a fair assumption, but may be wrong. It could be improved by having the dependency generator use the regular `-o` argument, when given on the command line.

### CODE REVIEW

**Comment by hth313** [comment]
As mentioned on the Foenix Discord, I think `--dependencies` should not generate normal compiler output, at least that is the way I read the Clang documentation.

It seems the `-MT` exists for the purpose of setting the output file for dependency generation. I am thinking that  if `-MT` is not given and `-o` is, that I could put together a `-MT<output-file>` taking the output file from  `-o`. Does that sound like a good solution?

I compared the `-MT` and `-MQ` options and I cannot see any difference. A quick googling did not make me any wiser either, why does `-MQ` exist?

**Comment by micjph** [comment]
I think that sounds like a good solution. `-MQ` seems like a safer option, it appears to quote any Make special characters:

```
-MQ target
    Same as -MT, but it quotes any characters which are special to Make.  -MQ '$(objpfx)foo.o' gives
       $$(objpfx)foo.o: foo.c
    The default target is automatically quoted, as if it were given with -MQ.
```

I was unaware that `-MT` and `-MQ` were already available. `-MQ<name>` works fine already, although it was a little confusing that it the option and argument must not be separated by a space.

**Comment by csoren** [comment]
I think generating -MQ/-MT from -o is a good fallback solution. I wasn't aware that `-MQ` was already exposed but it works fine, although it was a little confusing that the option does not accept a space between it and its argument.

Apparently `-MQ` quotes some Make specific characters

```
-MQ target
    Same as -MT, but it quotes any characters which are special to Make.  -MQ '$(objpfx)foo.o' gives
        $$(objpfx)foo.o: foo.c
    The default target is automatically quoted, as if it were given with -MQ.
```

The Makefile has been updated with -MQ. I'm happy with this solution

**Comment by csoren** [comment]
Thinking about this, I no longer think generating `-MQ` from `-o` is a good idea. If anything, I think the `--dependencies -o name` combo should put `name` into clang's `-MF` option, so it writes to that file instead of stdout.

**Comment by hth313** [comment]
Do you think that I should use `-MQ` rather than `-MT` when I inherit the name from `-o`?

**Pull request merged**
